#version 430

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout (binding = 0, rgba8) uniform image2D inputImage;
layout (binding = 1, rgba8) uniform image2D outputImage;
layout(std430, binding = 2) buffer MatrixBuffer {
    int matrix[];
};

uniform int matrixSize;
        
void main()
{
    ivec2 coords = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = vec4(0.0);
    
    int currentMatrixSize = matrixSize/2;
    
    int totalWeight = 0;
    
    for (int i = -currentMatrixSize; i <= currentMatrixSize; i++)
    {
        for (int j = -currentMatrixSize; j <= currentMatrixSize; j++)
        {
            ivec2 offset = ivec2(i,j);
            vec4 colorBlurred = vec4(imageLoad(inputImage, coords + offset).xyz, 1.0);
            
            color += colorBlurred * matrix[(i + currentMatrixSize) * matrixSize + j + currentMatrixSize];
            
            totalWeight += matrix[(i + currentMatrixSize) * matrixSize + j + currentMatrixSize];
        }
    }
    
    if(totalWeight != 0) {
        color = color/ totalWeight;
    } else {
        color.a = 1.0;
    }
    imageStore(outputImage, coords, color);
}